export const POSTS_SET_DATA = 'POSTS_SET_DATA';
export const POSTS_SET_LOADING = 'POSTS_SET_LOADING';
export const VISITED_ADD_POST = 'VISITED_ADD_POST';
export const LAYOUT_TOGGLE_SIDEBAR = 'LAYOUT_TOGGLE_SIDEBAR';
export const POSTS_DISMISS = 'POSTS_DISMISS';
export const POSTS_DISMISS_ALL = 'POSTS_DISMISS_ALL';
export const POSTS_SELECT = 'POSTS_SELECT';
