export enum Action {
  POSTS_SET_DATA = 'POSTS_SET_DATA',
  POSTS_SET_LOADING = 'POSTS_SET_LOADING',
  VISITED_ADD_POST = 'VISITED_ADD_POST',
  LAYOUT_TOGGLE_SIDEBAR = 'LAYOUT_TOGGLE_SIDEBAR',
  POSTS_DISMISS = 'POSTS_DISMISS',
  POSTS_DISMISS_ALL = 'POSTS_DISMISS_ALL',
  POSTS_SELECT = 'POSTS_SELECT',
}
